- name: prepare infra for deploy
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: create node
    terraform:
      force_init: True
      project_path: "./"
      variables:
        openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        openstack_username: "{{ lookup('env','OS_USERNAME') }}"
        openstack_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"

        node_volume_name: "{{ node_volume_name | default('khrustalyov_infra_terra_ansible') }}"
        node_name: "{{ node_name | default('khrustalyov_infra_terra_ansible') }}"
        key_name: "{{ key_name }}"
        image_name: "{{ image_name }}"
        flavor_name: "{{ flavor_name }}"
        network_name: "{{ network_name }}"
    environment:
        TF_VAR_openstack_password: "{{ lookup('env','OS_PASSWORD') }}"
    register: infra_creation_out

  - name: get node ip4
    add_host:
      name: "{{ infra_creation_out.outputs.node_ip.value }}"
      group: artstyle_nodes
      ansible_user: ubuntu
      ansible_ssh_key_file: ~/OpenSKey
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  
  - name: render arstyle nodes invenory file
    template:
      src: ./artstyle_nodes_temp.j2
      dest: ./artstyle_nodes_temp.ini

  - name: wait for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ infra_creation_out.outputs.node_ip.value }}'
      search_regex: OpenSSH
      delay: 10

- name: configure artstyle nodes
  hosts: artstyle_nodes
  become: True
  tasks:
    - name: update packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: download docker install script
      get_url:
        url: https://get.docker.com
        dest: ~/get-docker.sh
        mode: "0100"

    - name: install docker
      shell: ~/get-docker.sh

    - name: check if docker group exists
      command: getent group docker
      register: docker_group
      ignore_errors: true

    - name: create docker group
      group:
        name: docker
        state: present
      when: docker_group.rc != 0

    - name: add user 'ubuntu' to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes



      