- name: prepare infra for deploy
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: create node
    terraform:
      force_init: True
      overwrite_init: True
      project_path: "."
      variables:
        openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        openstack_username: "{{ lookup('env','OS_USERNAME') }}"
        openstack_password: "{{ lookup('env','OS_PASSWORD') }}"
        openstack_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"

        node_volume_name: "{{ node_volume_name | default('khrustalyov_infra_terra_ansible') }}"
        node_name: "{{ node_name | default('khrustalyov_infra_terra_ansible') }}"
        key_name: "{{ key_name }}"
        image_name: "{{ image_name }}"
        flavor_name: "{{ flavor_name }}"
        network_name: "{{ network_name }}"
    register: infra_creation_out
