- name: prepare infra for deploy
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: create node
    terraform:
      force_init: True
      project_path: "./"
      variables:
        openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        openstack_username: "{{ lookup('env','OS_USERNAME') }}"
        openstack_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"

        node_volume_name: "{{ node_volume_name | default('khrustalyov_infra_terra_ansible') }}"
        node_name: "{{ node_name | default('khrustalyov_infra_terra_ansible') }}"
        key_name: "{{ key_name }}"
        image_name: "{{ image_name }}"
        flavor_name: "{{ flavor_name }}"
        network_name: "{{ network_name }}"
    environment:
        TF_VAR_openstack_password: "{{ lookup('env','OS_PASSWORD') }}"
    register: infra_creation_out

  - name: get node ip4
    add_host:
      name: "{{ infra_creation_out.outputs.node_ip.value }}"
      group: artstyle_nodes
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/OpenSKey
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: configure artstyle nodes
  hosts: artstyle_nodes
  tasks:
    - setup:
      register: setup_status
      until: setup_status is success
      delay: 10
      retries: 30
    - name: update packages
      apt:
        update_cache: yes
        upgrade: yes
      become: True
    - name: download docker install script
      get_url:
        url: https://get.docker.com
        dest: ~/get-docker.sh
        mode: "0100"
      become: True
    - name: install docker
      shell: ~/get-docker.sh
      become: True



      